name: cosc595-implementation
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python
  - pytorch
  - torchvision
  - pytorch-cuda
  - numpy
  - pandas
  - scikit-learn
  - pillow
  - matplotlib
  - seaborn
  - tqdm
  - jupyter
  - ipykernel
  - kaggle
  - pip
  - pip:
      - torchinfo